### ISSUE TITLE
Docker container won't start: onfhir-server-standalone.jar missing

### ISSUE THREAD

**Issue by beanformer** [srdc/onfhir#39]
Utilizing the configuration in the [/docker](https://github.com/srdc/onfhir/tree/master/docker) directory, the Docker container won't start because `onfhir-server-standalone.jar` is missing.

It is obviously the FHIR server core referenced in line 73 of docker-entrypoint.sh:
```
JAVA_CMD+="/fhir/onfhir-server-standalone.jar".
```

**Comment by tnamli** [comment]
Hi Matthias,

You need to compile/package the onfhir and then copy the jar to the docker folder before building/running the docker scripts. You can check the related Docker section in the README  file. Please let me know if you still have problems after doing this.

**Comment by tnamli** [comment]
I assume this is closed, please reopen it if your problem is not solved.

**Comment by tnamli** [comment]
I assume this is closed, please reopen it if your problem is not solved.

**Comment by beanformer** [comment]
Thanks Tuncay. The suggested way works, but a prepared Docker image would not be bad either.
